# Generated by Django 4.0.4 on 2022-05-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_status',
            field=models.ForeignKey(choices=[('register', 'Register'), ('register_complete', 'Register Complete'), ('complete', 'Complete')], max_length=20, on_delete=django.db.models.deletion.CASCADE, to='support.answer'),
        ),
    ]
